use_frameworks!

platform :ios, '10.0'

target 'GXCaptureVideo_Example' do
  pod 'GXCaptureVideo', :path => '../'

  target 'GXCaptureVideo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
